#uses ubuntu as the base
FROM python:3.10.7

WORKDIR /ResponseNet
RUN wget https://raw.githubusercontent.com/Reed-CompBio/ResponseNet/main/responsenet.py
RUN pip install ortools && pip install networkx==3.3